AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: A hello world application.
Resources:
  ImageThumbFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: bin/image-thumb
      Runtime: go1.x
      Events:
        ImageThumb:
          Type: Api
          Properties:
            Path: /image-thumb
            Method: get
